[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"
  NODE_VERSION = "18"

[context.deploy-preview]
  command = "yarn build-preview"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "/.well-known/webfinger/index.json"
  status = 200
  force = true