backend:
  name: git-gateway

media_folder: "site/content/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: Tags
        name: tags
        widget: list
        required: false
  - name: "hamlets-danish-comic" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Hamlet's Danish Comic" # Used in the UI, ie.: "New Post"
    folder: "site/content/hamlets-danish-comic" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: Tags
        name: tags
        widget: list
        required: false
  - name: "ghostcat-comics-archive" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Ghostcat Comics" # Used in the UI, ie.: "New Post"
    folder: "site/content/ghostcat-comics-archive" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: Tags
        name: tags
        widget: list
        required: false
  - name: "raecomic" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Rob and Elliot Comic" # Used in the UI, ie.: "New Post"
    folder: "site/content/raecomic" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: Tags
        name: tags
        widget: list
        required: false
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Banner", name: "banner", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - file: "site/content/gallery/_index.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown", required: false}
          - label: Gallery
            name: galleries
            widget: list
            required: false
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: Show Full Image
                name: fullimage
                widget: boolean
                default: false
              - label: Entries per row
                name: rownum
                widget: "number"
                default: 4
                valueType: "int"
                min: 1
                max: 6
              - label: Entry
                name: gallery
                widget: list
                required: false
                fields:
                  - label: Title
                    name: title
                    widget: string
                    required: false
                  - label: Image
                    name: image
                    widget: image
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/hamlets-danish/_index.md"
        label: "Hamlets Danish Page"
        name: "hamlets-danish"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
      - file: "site/content/ghostcat-comics/_index.md"
        label: "Ghostcat Comics Page"
        name: "ghostcat-comics"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}